### ISSUE TITLE
Use timestamps for epochs

### ISSUE THREAD

**Issue by to-sh-1** [shapeshift/foxy#103]
Currently we are using block.number to calculate our epochs.

our current epoch struct looks like this:

`
epoch = Epoch({
            length: uint,
            number: uint,
            endBlock: uint,
            distribute: uint
        });
`

We need to change this to use timestamps instead of block.  Replace number with timestamp and endBlock with endTime.

rebase should check against block.timestamp vs block.number

This is due to being able to bridge to other chains that do not have a set time for blocks.  
It will also help use time our rebases more accurately.

**Comment by 0xean** [comment]
closing in favor of #112 for bounty!
