### ISSUE TITLE
Staking Contract: Abstract TOKE deposit / withdrawal

### ISSUE THREAD

**Issue by to-sh-1** [shapeshift/foxy#17]
There will be many different protocols implemented to FOXy, we need to abstract the functions to be able to add/remove protocols easily

**Comment by gomesalexandre** [comment]
What would be examples of other protocols we could support? I suppose their interface and withdrawal methods would be different from `ITokePool` ? In other words, do we want to be able to be able to make withdraw/deposit (and also probably abstract balance retrieval) calls from contracts we'll add in the future and which interfaces are unknown ahead of time?

**Comment by to-sh-1** [comment]
As per our discussion on discord: The methods will be different than TokePool, but it will be fine to hold off on going too deep in planning these calls for only V1
